# Generated by Django 4.0.6 on 2022-07-26 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_register', '0002_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemName',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serialNum',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
