# Generated by Django 4.0.6 on 2022-07-26 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_register', '0004_warehouse_warehouselocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemCode',
            field=models.CharField(default='UNKNOWN', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemName',
            field=models.CharField(default='UNKNOWN', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serialNum',
            field=models.CharField(default='UNKNOWN', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
